baseURL = 'https://benjaminsong90.github.io/'
languageCode = 'zh-cn'
title = '宋浪的博客'
theme = 'paper'
copyright = "© 2025, songlang"

[params]
    favicon = "/favicon.ico"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10